import type { Metadata } from "next";
import "./globals.css";
import "../styles/utilities.css"
import { inter, poppins } from "@/styles/fonts";
import ReduxProvider from "@/redux/provider";
import AuthProvider from "@/components/auth/auth-provider";

export const metadata: Metadata = {
  title: "Travel Genie AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} font-inter text-sm bg`}
      >
        <ReduxProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
