import type { Metadata } from "next";
import "./globals.css";
import { inter, poppins } from "@/styles/fonts";
import ReduxProvider from "@/redux/provider";
import AuthProvider from "@/components/auth/auth-provider";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Travel Genie AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} font-inter text-sm bg`}
      >
        <Providers>
          <ReduxProvider>
            <AuthProvider>{children}</AuthProvider>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
